name: Build Release APK Gratis

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Inisialisasi Android & Patch Kotlin & SDK
        run: |
          # 1. Hapus android lama agar tidak ada residu konfigurasi usang
          rm -rf android
          
          # 2. Generate android dengan Flutter 3.22 (Bawaan resmi Kotlin 1.9+)
          flutter create . --org id.go.menlhk --project-name hydro_surveyor --platforms android
          
          # 3. Kunci minSdkVersion ke versi 21 (wajib untuk plugin camera)
          find android/ -name "build.gradle" -exec sed -i 's/minSdkVersion = flutter.minSdkVersion/minSdkVersion = 21/g' {} +
          find android/ -name "build.gradle" -exec sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' {} +

          # 4. Berikan izin eksekusi gradlew
          if [ -f android/gradlew ]; then
            chmod +x android/gradlew
          fi

      - name: Ambil Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HydroSurveyor-v1.0-Release
          path: build/app/outputs/flutter-apk/app-release.apk
